build:
    dependencies: {}
    source_srs: 2230
dependencies: {}
extract: {}
sources:
    cities:
        url: http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip
    sd_communities:
        url: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
    sd_councils:
        url: http://rdw.sandag.org/file_store/District/Council_Districts.zip
    sd_neighborhoods:
        description: San Diego Neighborhoods. A cached version, since SANGIS seems
            to have removed the file.
        url: http://ds.civicknowledge.org/sangis.org/Community/Neighborhoods_SD.zip
