build: {}
dependencies: {}
extract: {}
sources:
    sdcommunities:
        description: null
        url: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
    sdneighborhoods:
        description: San Diego Neighborhoods. A cached version, since SANGIS seems
            to have removed the file.
        url: http://ds.civicknowledge.org/sangis.org/Community/Neighborhoods_SD.zip

