build:
    dependencies: {}
    sources:
        sdcommunities: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
        sdneighborhoods: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.ZIP
dependencies: {}
extract: {}
sources:
    sdcommunities:
        description: null
        url: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
    sdneighborhoods:
        description: null
        url: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.ZIP
views:
    communities:
        communities_norm: SELECT OGC_FID as id, cpname as name, AsText(geometry) as
            wkt, Area(geometry) as area FROM communities
    neighborhoods:
        neighborhoods_norm: SELECT OGC_FID as id, name, AsText(geometry) as wkt, Area(geometry)
            as area FROM neighborhoods
