build:
    dependencies: {}
    sources:
        municipal: http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip
        publicsafety: http://rdw.sandag.org/file_store/Jurisdiction/Public_Safety_Jurisdictions.zip
        reservations: http://rdw.sandag.org/file_store/Jurisdiction/Indian_Reservations.zip
        sra: http://rdw.sandag.org/file_store/Jurisdiction/Subregional_Areas_2010.zip
dependencies: {}
extract: {}
sources:
    municipal:
        description: null
        url: http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip
    publicsafety:
        description: null
        url: http://rdw.sandag.org/file_store/Jurisdiction/Public_Safety_Jurisdictions.zip
    reservations:
        description: null
        url: http://rdw.sandag.org/file_store/Jurisdiction/Indian_Reservations.zip
    sra:
        description: null
        url: http://rdw.sandag.org/file_store/Jurisdiction/Subregional_Areas_2010.zip
