build: {}
dependencies:
    places: sandiegodata.org-places-casnd-places-geo
    communities:  sangis.org-neighborhoods-orig-sdcommunities-geo
    parcels: sangis.org-parcels-orig-parcels-geo
extract: {}
sources:
    parcels:
        url: http://rdw.sandag.org/file_store/Parcel/Parcels.zip
views: {}
