build:
    dependencies: {}
    sources:
        businesses: http://rdw.sandag.org/file_store/Business/Business_Sites.zip
dependencies: {}
extract: {}
sources:
    businesses:
        description: null
        url: http://rdw.sandag.org/file_store/Business/Business_Sites.zip
