build:
    codes: meta/codes.yaml
    dependencies: {}
    schema_file: meta/schema.csv
    zips: meta/zips.yaml
dependencies: {}
extract: {}
sources:
    addresses:
        url: http://rdw.sandag.org/file_store/Address/Address_APN.zip
    intersections:
        url: http://rdw.sandag.org/file_store/Transportation/Roads_Intersection.zip
    roads:
        url: http://rdw.sandag.org/file_store/Transportation/Roads_All.zip
