about:
    author: City of San Diego, General Services Dept., Street Division
    description: !include 'config/about.description.md'
    documents:
    -   description: The terms and conditions that apply to the original shapefiles.
            Users must accept these terms before using the file.
        title: Terms and Conditions
        url: http://www.sangis.org/Legal_Notice.htm
    -   description: The PDF file of metadata for the Municipal Boundaries shapefile.
        source: cities
        title: Municipal Boundaries metadata
        url: http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.pdf
    -   source: sdcommunities
        title: null
        url: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.pdf
    -   source: sdneighborhoods
        title: null
        url: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.pdf
    -   description: null
        source: sdcouncil
        title: null
        url: http://rdw.sandag.org/file_store/District/Council_Districts.pdf
    -   description: null
        source: sdmad
        title: null
        url: http://rdw.sandag.org/file_store/District/Maintenance_Assessment_Districts_SD.pdf
    homepage: http://rdw.sandag.org/Default.aspx?dir=Miscellaneous
    license: other-open
    maintainer: City of San Diego, General Services Dept., Street Division
    tags:
    - government
    - gov-infrastructure
    title: Municipal Boundaries
build:
    sources:
        city: http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip
        sd_community: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
        sd_council: http://rdw.sandag.org/file_store/District/Council_Districts.zip
        sd_neighborhood: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.ZIP
identity:
    creator: eric@sandiegodata.org
    dataset: places
    id: a2RX3O
    name: sangis.org-places-orig-429e
    revision: 1
    source: sangis.org
    variation: orig
partitions:
- sangis.org-places-orig-429e-city_orig
- sangis.org-places-orig-429e-sd_community_orig
- sangis.org-places-orig-429e-sd_council_orig
- sangis.org-places-orig-429e-sd_neighborhood_orig
- sangis.org-places-orig-429e-places
views:
    places:
        places_norm: SELECT code as id, name, AsText(geometry) as wkt, Area(geometry)
            as area FROM places
