build:
    sources:
        sdcommunities: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
        sdneighborhoods: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.ZIP
identity:
    creator: eric@sandiegodata.org
    dataset: neighborhoods
    id: a2Ol01
    name: sangis.org-neighborhoods-orig-429e
    revision: 1
    source: sangis.org
    variation: orig
partitions:
- sangis.org-neighborhoods-orig-429e-neighborhoods.sd
- sangis.org-neighborhoods-orig-429e-communities.sd
views:
    communities:
        communities_norm: SELECT objectid as id, cpname as name, AsText(geometry)
            as wkt, Area(geometry) as area FROM communities
    neighborhoods:
        neighborhoods_norm: SELECT objectid as id, name, AsText(geometry) as wkt,
            Area(geometry) as area FROM neighborhoods
